# عينات بريد إنجليزية واقعية (أنماط شائعة في تصنيفات البريد) للتدريب عند عدم توفر ملف خارجي.
PHIS = [
    'URGENT: Your online banking will be closed. Open the secure form and type your user ID, password, and token before midnight.',
    'Security alert: PayPal detected login from a new country. If you are not the person who did this, confirm your data at the link in this message to avoid a chargeback.',
    'You have an undeliverable DHL item. A customs charge must be paid within 12 hours. Use this payment portal. Failure will result in return to sender.',
    'The IRS is applying your refund. Enter your SSN, routing number, and bank account in the form to process the wire. This page will expire in 2 hours only.',
    'WhatsApp: your number will be disconnected unless you verify. Install the new certificate from the file attached. Enable macros in Word if the system asks for it.',
    'LinkedIn: your profile is limited because we found unusual profile views. Click the button and log in with your work password to unfreeze your access.',
    'We locked your iCloud. Your photos and contacts may be deleted. Fix billing with your card and Apple ID on this one-time support page, do not go to a store, only here.',
    'Coinbase: activity alert. 0.2 BTC is leaving your wallet. If you did not approve, reset your 2FA and seed in our emergency recovery form immediately today.',
    'HR notice: you must read the compliance PDF and enable editing to sign. The IT team needs this for audit. The policy update is in the document attached, double click the icon.',
    'Microsoft 365: your password has expired. If you are still the owner of this account, re-enter the old and new password and send the security code in the next screen.',
    'Amazon: your last card failed. We will auto-cancel your subscription and delete wishlists in 1 day. Go to the fake-looking link only from this message to not lose orders.',
    'Your Netflix membership will stop today. A payment of 0.00 is not enough. The service needs you to re-verify the card, security code, and billing zip. Act now, only today.',
    'Bank AlAhli: your token device is not synced. We need your national ID, card PIN, and CV2 for new regulations. The secure server will close at 4 PM, after that, wire stops.',
    'Hello team, the CEO asked me to send a wire. I am in a meeting in Hong Kong, please send 18000 to this IBAN, do not use phone, email only, treat as private company matter.',
    'Google security: device added in Nigeria. You must confirm or all Gmail will be deleted. Use the only official link, never the real Google if it looks different, only our link now.',
    'Chase: validate online session. A device in Texas accessed your check images. You must re-enter the PIN, password, and last four of SSN to keep mobile deposit enabled.',
    'Facebook: your business page is reported. To appeal, send your password and 2FA backup codes. Our automated review is strict, so include a photo of your ID, front and back.',
    'Apple receipt: 499 for iCloud, if this was not you, open dispute form and add your iCloud password and full card, our fraud team will call you, use only this form here please.',
    'FedEx: your label was printed wrong. A second delivery fee of 2.50 is required. The tracking number will stop working. Pay by card, no cash, the button is the only way now.',
    'Zoom: a meeting is recorded for your account. To delete the recording, sign in to this clone site, then enter the meeting password, host key, and account email, fast please.',
    'Spotify: your free trial is ending, but we can extend if you re-enter a card and password to prove identity. The charge is a temporary hold, not a real charge, trust us, click.',
    'Dropbox: your shared folder has illegal files. A lawyer will be contacted. To delete the false claim, pay a small service fee, then upload your ID. The link to pay is the last line in this text.',
    'Stripe: a dispute was opened. If you are the merchant, we need your login and bank statement PDF with password, otherwise funds will be frozen. Use our portal only, not Stripe com.',
    'Office 365: shared document needs your signature, open the link, the document may ask for permissions, that is expected, the macro helps display the form for sign off today.',
    'Instagram: a copyright strike was filed. In 3 hours, your account is gone. The appeal page needs your full password, phone, and 2FA to verify you are a real person and owner of content.',
    'Bank fraud unit: a wire was initiated from your account. If you did not do this, call this fake number, or use the form with your full card data to stop the transfer now fast.',
    'Steam: a rare item is waiting, log in to claim, the login page is steamcommunity-community.ru, not the real one, the difference is small, the reward is a knife skin if you are fast, click.',
    'DocuSign: a contract is ready. Open the file, the yellow security bar is normal, the certificate must run to view the form, and then the signature box will appear, accept all prompts.',
    'Mail delivery failed, your mailbox is 99% full, click expand storage, you must install the plugin from the helpdesk link, it is safe, IT said so, your manager was copied on a fake email.',
    'Bitdefender scan found 12 viruses, download the cleaner, run as admin, the cleaner needs your email password to remove rootkits, this is a known procedure for premium users only, trust IT.',
    'HR payroll: a bonus was posted, click to see amount, the PDF is password protected, the password is your employee ID, if it fails, use your SSN, then enable editing to read your bonus, okay.',
    'Urgent: your domain will be suspended, pay renewal now to this wallet address, 0.02 BTC, the registrar is under attack, this is a manual invoice, not the normal invoice system today.',
    'Zoom billing: a refund of 3.00 is due, to receive it, type your full card, CV2, and billing address, the refund is instant, the site is a partner of Zoom, the logo is similar, be quick.',
    'Google Photos: 12 people opened your private album, if this was not you, add your account password, then a code will be sent, then your album will be private again, only from this help link.',
    'Etsy: a buyer left a bad review, to remove, pay a 5 dollar med fee, the link is not Etsy, the brand name is a typo, the fee is a security deposit, the review will be hidden after payment, maybe.',
    'Wells Fargo: a device was set as trusted, if you did not, open this special tool, the tool is a .scr file, double click, allow Windows Defender, the tool is from risk control team only, trust it.',
    'WeChat: a friend added you, open the add link, the link asks for a scan of your ID, the scan is to fight bots, the friend is not a bot, the ID is for safety of all users, complete form now.',
    'Adobe: a PDF needs your signature, the PDF is actually an exe renamed, the icon is PDF, run it, the macro does e-sign, the macro is a known Adobe helper, the antivirus is wrong, add exception.',
    'GitHub: a secret was exposed, rotate token now, the link to rotate is a clone of GitHub, the URL is github-security.ru, the login is the same, the site will save your new token, trust us, login.',
    'Slack: your workspace is deleted for policy, the appeal form is a Google Form clone, the form needs your work password, your Slack export, and a photo of your badge, 24h deadline, hurry.',
    'Airbnb: a booking is pending payment, a wire is the only way, do not use the app, the host needs cash today, the wire details are in the next email, the host name is a generic bank, send today.',
    'Uber: a ride charge failed, a legal fee is added, pay the small fee, the link is not Uber, the logo is close, the fee is to unlock your account, or you are banned, pay now, small amount only.',
    'McAfee: 14 viruses, renew now, the renew page is not McAfee, the price is 9.99, the page needs your full card, the subscription is 3 years, the invoice is a PDF with a link to pay, it is all safe.',
    'Twitter: a copyright claim, send your password, the support account is a verified blue check, the check is fake, the DMCA form needs your real password, or your account is gone in 1 hour, send.',
    'Oracle Cloud: a bill of 0.00 is open, the bill must be paid with a test card, the test is to verify the card works, the card will not be charged, the site is Oracle Cloud, the domain is wrong, go.',
    'Docusign: an envelope was sent, the envelope is a .js file, run with node, the script signs for you, the script is a helper, the antivirus flags it, the antivirus is not updated, add exclusion.',
]

HAM = [
    'Thank you for your purchase. Your order 90211 will ship in two business days. Tracking will be in your account. The receipt is attached as a PDF, no action required, enjoy your new gear.',
    'Meeting: stand-up at 9:15 in room 4. Please update your Jira before the start. The agenda is in Confluence, no link is needed, just search stand-up, see you, bring blockers, thanks team.',
    'Your dentist visit is on Thursday at 3:30. Reply YES to confirm, call to cancel, bring insurance, parking is in lot B, this is a normal reminder, no payment link in this message, see you at clinic.',
    'Your water bill of 32.10 was auto-paid from the card ending 4412. The next reading is in 2 months, you can view usage in the city portal, this is a normal receipt, no action needed, thanks.',
    'The newsletter this week: local events, a book club meetup, and a new cafe review. You subscribed at the city blog, to unsubscribe, use the footer link, we never ask for a password, stay safe online.',
    'Your registration is confirmed: workshop "Intro to data privacy" on May 1 at 10 AM, room 8, free session, no payment, bring a laptop, coffee is in the hall, a calendar invite is attached as ICS, ok.',
    'Support case 12033 is closed. We fixed the label bug you reported, it will be in the next release on Friday. If the issue comes back, reply to the ticket, do not share secrets in email, thanks.',
    'Your flight AA 245 is on time, gate C12, boarding at 1:20 PM, seat 14C, a carry-on is allowed, if you need a change, use the app, this is an automated message from the carrier, not a promo email.',
    'The quarterly all-hands deck is in the shared drive under Q1 folder. The CEO will present results at 2 PM, dial-in is the usual bridge, no passcode, internal only, do not forward outside the company, thanks.',
    'Your return label for order 55 is ready, drop at any post office, refund in 5 days after scan, a prepaid code is in your order page, this email is a simple confirmation, we do not need your card again.',
    'Library: the book you reserved is now available, pick it up in 3 days, after that it will go to the next person, the library does not need payment, your card on file is only for late fees, if any, thanks.',
    'Your class grade is posted in the LMS, log in to see feedback, the grade is FERPA protected, this email is not a grade update, the full text is in the system only, for questions email the TA, not your password, ok.',
    'Charity: thank you for your 25 donation, a receipt is attached, the charity is 501c3, keep for taxes, you can set recurring giving in the portal, this message is a thank you, we never ask to wire, thanks.',
    'Your domain renewal is due in 30 days, the normal registrar is Namecheap, log in to your account, the price is on the page, this email is a real reminder, do not use links in random email, go to the site, ok.',
    'Your kid school lunch balance is 12, you can add funds in the app, the school will not call for gift cards, this message is from the real school domain, for help call the main office, not a random number, be safe.',
    'Your subscription to the journal ends next month, renew in account settings, the price is the same, the journal does not need your card by email, only on the site, this is a kind reminder, not a pay link, ok.',
    'The HOA meeting is next Tuesday, agenda includes parking and roof repair, a PDF is on the community site, the board will not ask for a wire, only dues through the normal portal, this email is a notice, thanks.',
    'Your blood test result is in the patient portal, log in, we do not send full results in email, the portal is the only way, the clinic will not ask for a password in a call, be careful of scams, call our main line, ok.',
    'The package from Amazon shows delivered at 2:14 PM, if you did not get it, check with neighbors, the carrier is UPS, the tracking in this email is a copy, the real one is in your account, this is a delivery note, not a request for money, ok.',
    'Your car service is done, the invoice is 240 for oil and filter, you can pay at pickup, the shop will not text you a random link, this email is a normal receipt, the shop phone is 555-0100, call if a question, thanks.',
    'The gym: your membership is active until year end, winter hours start Monday, the pool is closed for maintenance Tuesday, the front desk will not ask for a card in email, this is a service note, be well.',
    'Your open source pull request was merged, thanks for the fix, the bot will release a patch, no need to open a new PR, the maintainers are volunteers, the discussion is in GitHub only, this email is a notice, cool.',
    'The book club: next read is a novel, 300 pages, meet in the cafe on Sunday at 3, RSVP in the group chat, the cafe will not need a wire, this email is a schedule, the club is not official, be nice, have fun, ok.',
    'Your local tax statement is in the city portal, log in, the city will not call for a gift card, the portal URL is on the city site, this email is a generic reminder, follow official channels only, stay safe, thanks.',
    'The WiFi at the office is updated, the new name is the same, the password is in the internal wiki, the IT will not text you a link, it is a policy, if asked for a link, report to IT, this email is from IT, for real, ok.',
    'Your team stored files are backed up, you can request restore in a ticket, the restore is free, the ticket system is the only place, a tech will not ask for your personal password, this is a process note, thanks.',
    'The campus alert is a test, ignore the sound, a real alert will be short, the campus will not ask for a wire, this email is a test follow-up, be aware of drills, the safety team sent this, be calm, ok.',
    'The museum ticket you bought is valid for 6 months, a QR is in the PDF, the museum will not ask to pay again, this email is a copy of your ticket, if lost, reprint from account, not from a new link, be careful, enjoy.',
    'Your survey response was saved, the survey is anonymous, we do not need your name in the tool, a prize draw is not real in email, this message is a system receipt, the survey link was official, be safe, thanks.',
    'The open house is Saturday, address is 10 Main St, a map is on the real estate site, the agent will not text a random wire, this email is a normal invite, verify agent license on the site, go safe, see you maybe.',
    'Your class materials are in Canvas, the first lecture slides are a PDF, the professor will not ask for a gift, this email is a course note, the syllabus is in Canvas, the email is a welcome, be ready, good luck, ok.',
    'The refund for your return was 48.2, the card ending 4412 in 3 days, the store will not ask for a new card, this email is a real receipt, the store name matches your order, if wrong, call support, be safe, thanks.',
    'The volunteer day is Sunday, meet at 8 AM, tools will be there, the org will not ask for a bank wire, this email is a sign-up, the org website is the source of truth, come if you can, have water, be safe, ok.',
    'The code review: please fix the null check in auth.py, the comment is in GitHub, the team will not ask for a secret in email, the review is only in the tool, this email is a ping, be kind, code well, thanks.',
    'The clinic flu shot: walk-in hours are 8 to 4, no appointment for flu, bring insurance, the clinic will not ask for a pre-pay link, this email is a public health note, the clinic phone is in the site, be safe, ok.',
    'The school play tickets are 10 each, pay at the door, the school will not only accept wire, this email is a save the date, the PTO is parent run, the money helps kids, the email is a notice, be happy, go art, ok.',
    'The public transit pass auto-renewed, the amount is 80, a receipt is in the app, the agency will not ask for a new card in email, this message is a service note, the app is the real place, travel safe, thanks.',
    'The farm share box is ready, pick up 4 to 6, bring your bag, the farm will not text a Zelle, this email is a real pickup note, the farm name matches your sign-up, if odd, call the number on the site, be safe, enjoy food.',
    'The coding boot camp: your cohort starts Monday, links are in the student portal, the school will not ask for a wire in a new domain, this email is an onboarding, use only the portal, be careful of clones, be ready, good luck.',
    'The city alert: water main work on 5th St, a detour is posted, the city will not ask for a fee in email, this is a public works note, the city site has a map, drive slow, the email is a notice, be patient, ok.',
    'The alumni email: a reunion in June, RSVP on the real alumni site, the school will not need a pre-pay gift card, this email is a kind invite, verify the .edu site, the email is a notice, see old friends, be safe, ok.',
    'The open source project: a security update is 2.1.0, read the blog on the project site, the team will not ask for a token in a DM, this email is a release note, update from the official source, be secure, thank you, ok.',
    'The coffee subscription shipped, roast is medium, if wrong roast, use the help page, the roaster will not text a wire, this email is a tracking note, the carrier is FedEx, the box is 2 lb, enjoy, and sleep well, thanks.',
]

def expanded_rows():
    rows = []
    for i, t in enumerate(PHIS):
        rows.append((t + f' [variant p-{i}]', 1))
    for i, t in enumerate(HAM):
        rows.append((t + f' [variant h-{i}]', 0))
    for j in range(12):
        for k, t in enumerate(PHIS):
            rows.append((t + f' noise-{j} ref-{k} domain cluster phishing pattern batch', 1))
        for k, t in enumerate(HAM):
            rows.append((t + f' noise-{j} ref-{k} domain cluster legit pattern batch', 0))
    return rows
